package models;
// Generated 06-ene-2020 23:47:09 by Hibernate Tools 4.3.1.Final

/**
 * Faccion generated by hbm2java
 */
public class Faccion implements java.io.Serializable {

	private int faccionId;
	private String nombreFaccion;
	private String lore;

	public Faccion() {
	}

	public Faccion(int faccionId) {
		this.faccionId = faccionId;
	}

	public Faccion(int faccionId, String nombreFaccion, String lore) {
		this.faccionId = faccionId;
		this.nombreFaccion = nombreFaccion;
		this.lore = lore;
	}

	public int getFaccionId() {
		return this.faccionId;
	}

	public void setFaccionId(int faccionId) {
		this.faccionId = faccionId;
	}

	public String getNombreFaccion() {
		return this.nombreFaccion;
	}

	public void setNombreFaccion(String nombreFaccion) {
		this.nombreFaccion = nombreFaccion;
	}

	public String getLore() {
		return this.lore;
	}

	public void setLore(String lore) {
		this.lore = lore;
	}

}
