package models;
// Generated 06-ene-2020 23:47:09 by Hibernate Tools 4.3.1.Final

/**
 * Personaje generated by hbm2java
 */
public class Personaje implements java.io.Serializable {

	private int personajeId;
	private String nombrePersonaje;
	private Integer ataque;
	private Integer defensa;
	private Integer faccionId;

	public Personaje() {
	}

	public Personaje(int personajeId) {
		this.personajeId = personajeId;
	}

	public Personaje(int personajeId, String nombrePersonaje, Integer ataque, Integer defensa, Integer faccionId) {
		this.personajeId = personajeId;
		this.nombrePersonaje = nombrePersonaje;
		this.ataque = ataque;
		this.defensa = defensa;
		this.faccionId = faccionId;
	}

	public int getPersonajeId() {
		return this.personajeId;
	}

	public void setPersonajeId(int personajeId) {
		this.personajeId = personajeId;
	}

	public String getNombrePersonaje() {
		return this.nombrePersonaje;
	}

	public void setNombrePersonaje(String nombrePersonaje) {
		this.nombrePersonaje = nombrePersonaje;
	}

	public Integer getAtaque() {
		return this.ataque;
	}

	public void setAtaque(Integer ataque) {
		this.ataque = ataque;
	}

	public Integer getDefensa() {
		return this.defensa;
	}

	public void setDefensa(Integer defensa) {
		this.defensa = defensa;
	}

	public Integer getFaccionId() {
		return this.faccionId;
	}

	public void setFaccionId(Integer faccionId) {
		this.faccionId = faccionId;
	}

}
